public class Algebra<T>
{
    public string [ ] Name = new string [ ] { "Algebra", "Algebraic Structure", "Underlying Set", "Carrier Set", "Domain" };
    public static string [ ] Formula { get; private set; } = new string[] { "{0}{1}" };
    //private Set A { get; set; } = new Set(BigInteger.Zero);

    /*public Dictionary<string, List<object>>[] Entities = new Dictionary<string, List<object>>[2]
    {
        ["Operation"] = new List<Operation>(),
        ["Axiom"] = new List<Axiom>()
    };*/
}