using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace U.C
{
    public class Homomorphism
    {
        //, whose elements are called morphisms or maps or arrows.
        public static string [ ] Name = new string [ ] { "Homomorphism" };
        public static string [ ] Formula = new string [ ] { };
        /*public static Dictionary<string, object> [ ] Element = new Dictionary<string, object> [ ]
        {
            ["Morphism"] = new List<Morphism>(),
            ["Arrow"] = new List<Arrow>(),
            ["Map"] = new List<Map>()
        };*/
    }
}